theme: default
site:
  title: Willsthoughts
  website: https://willsthoughts.com

destination: .output
layout_dir: _layouts
template_dir: _templates
include_dir: _includes
themes_dir: _themes
block_list: [ ]
markdown_extensions:
  - .md
  - .markdown
permalink: date
show_drafts: false
output:
  posts_dir: posts
