title: Willsthoughts
url: https://willsthoughts.com
theme: aurora
site:
  website: https://willsthoughts.com
exclude:
  - README.md
  - config.*
include: []
destination: .output
layout_dir: _layouts
template_dir: _templates
include_dir: _includes
themes_dir: _themes
block_list: [ ]
markdown_extensions:
  - .md
  - .markdown
permalink: date
show_drafts: false
output:
  posts_dir: posts
pagination:
  enabled: true
  items_per_page: 9
  collection: posts
  permalink: /page/:num/
  indexpage: index
