name: gengen
description: A sample command-line application.
version: 0.5.0
repository: https://github.com/kingwill101/gengen
publish_to: none

environment:
  sdk: '>=3.9.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  artisanal: ^0.1.0
  build: ^4.0.2
  collection: ^1.19.1
  console: ^4.1.0
  crypto: ^3.0.6
  csv: ^6.0.0
  dot_prop: ^1.0.1
  file: ^7.0.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  glob: ^2.1.3
  highlight: ^0.7.0
  html: ^0.15.6
  html_unescape: ^2.0.0
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_path: ^0.8.0
  liquify: ^1.3.1
  logging: ^1.3.0
  lualike: ^0.0.1-alpha.2
  markdown: ^7.3.0
  mime: ^2.0.0
  more: ^4.6.1
  path: ^1.9.1
  routed: ^0.1.0
  rxdart: ^0.28.0
  sass: ^1.93.2
  toml: ^0.17.0
  web_socket_channel: ^3.0.3
  yaml: ^3.1.3

dev_dependencies:
  build_config: ^1.2.0
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.26.3

dependency_overrides:
  archive: 4.0.7
  crypto_keys: 0.3.0+1
  pointycastle: 3.6.2
executables:
  gengen: main

funding:
  - https://www.buymeacoffee.com/kingwill101
